<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fbp</string>
	</array>
	<key>name</key>
	<string>FBP</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>IIP string</string>
			<key>match</key>
			<string>'.+'</string>
			<key>name</key>
			<string>string.quoted.fbp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.operator.connection.fbp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.component.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Component with port on the left (optionally on the right too)</string>
			<key>match</key>
			<string>([A-Z0-9]+) (\w+)(\([\w\/\.\-]+\))?(?: ([A-Z0-9]+))?</string>
			<key>name</key>
			<string>variable.expression.fbp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.component.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Component with port on the right (optionally on the left too)</string>
			<key>match</key>
			<string>(?:([A-Z0-9]+) )?(\w+)(\([\w\/\.\-]+\))? ([A-Z0-9]+)</string>
			<key>name</key>
			<string>variable.expression.fbp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.source.fbp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.fbp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.declaration.fbp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.component.fbp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.access.fbp</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.fbp</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.naming.fbp</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.fbp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>External port declaration</string>
			<key>match</key>
			<string>((?:IN|OUT|EX)PORT)(=)(\w+)(\.)([A-Z0-9]+)(:)([A-Z0-9]+)</string>
			<key>name</key>
			<string>variable.expression.graph.inport.fbp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fbp</string>
	<key>uuid</key>
	<string>23cca992-559d-4b2b-9e97-81493d6c9de7</string>
</dict>
</plist>
